<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Antithesis.SDK" Version="2.0.4"/>
        <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.7" />
        <PackageVersion Include="Microsoft.Orleans.Client" Version="10.1.0" />
        <PackageVersion Include="Microsoft.Orleans.Clustering.AzureStorage" Version="10.1.0" />
        <PackageVersion Include="Microsoft.Orleans.Persistence.AzureStorage" Version="10.1.0" />
        <PackageVersion Include="Microsoft.Orleans.Sdk" Version="10.1.0" />
        <PackageVersion Include="Microsoft.Orleans.Server" Version="10.1.0" />
        <PackageVersion Include="Microsoft.Orleans.Transactions" Version="10.1.0" />
        <PackageVersion Include="Microsoft.Orleans.Transactions.AzureStorage" Version="10.1.0" />
        <PackageVersion Include="Polly.Core" Version="8.6.6" />
    </ItemGroup>
</Project>