<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <OrleansVersion>10.1.0</OrleansVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Antithesis.SDK" Version="2.0.4" />
        <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.7" />
        <PackageVersion Include="Microsoft.Orleans.Client" Version="$(OrleansVersion)" />
        <PackageVersion Include="Microsoft.Orleans.Clustering.AzureStorage" Version="$(OrleansVersion)" />
        <PackageVersion Include="Microsoft.Orleans.Persistence.AzureStorage" Version="$(OrleansVersion)" />
        <PackageVersion Include="Microsoft.Orleans.Sdk" Version="$(OrleansVersion)" />
        <PackageVersion Include="Microsoft.Orleans.Server" Version="$(OrleansVersion)" />
        <PackageVersion Include="Microsoft.Orleans.Transactions" Version="$(OrleansVersion)" />
        <PackageVersion Include="Microsoft.Orleans.Transactions.AzureStorage" Version="$(OrleansVersion)" />
        <PackageVersion Include="Polly.Core" Version="8.6.6" />
    </ItemGroup>
</Project>