###### Stage 1 of 2 - Build

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /app
COPY . ./
RUN dotnet restore Bank.Client/Bank.Client.csproj
RUN dotnet build Bank.Client/Bank.Client.csproj --configuration Release --no-restore
RUN dotnet publish Bank.Client/Bank.Client.csproj --configuration Release --no-build -o out

##### Stage 2 of 2 - Production Image

FROM mcr.microsoft.com/dotnet/runtime:10.0
WORKDIR /app
COPY --from=build /app/out .

# Symlink to the folder where Antithesis will automatically instrument the binaries.
RUN mkdir -p /opt/antithesis/catalog
RUN ln -s /app /opt/antithesis/catalog/app

# Copy our Test Composer scripts to the folder where Antithesis will find them.
# Change the scripts' permissions to allow them to be executed.
COPY test_composer /opt/antithesis/test/v1
RUN chmod -R +x /opt/antithesis/test/v1

ENTRYPOINT ["dotnet", "Bank.Client.dll"]
CMD ["BankClientOptions:Mode=Setup"]