services:
    azurite:
        image: mcr.microsoft.com/azure-storage/azurite:latest
        container_name: azurite
        restart: always
        # azurite has entrypoint = "docker-entrypoint.sh" with a cmd = ["azurite", ...]
        # We've overridden command to disable telemetry and go slient because of the noise that it produces.
        command: ["azurite", "-l", "/data", "--tableHost", "0.0.0.0", "--disableTelemetry", "--silent"]

    bankserver1:
        image: ${ANTITHESIS_REGISTRY}/orleans-bank-test/bankserver:${TAG}
        build:
            dockerfile: Dockerfile.server
        container_name: bankserver1
        restart: always
        depends_on:
            - azurite

    bankserver2:
        image: ${ANTITHESIS_REGISTRY}/orleans-bank-test/bankserver:${TAG}
        container_name: bankserver2
        restart: always
        depends_on:
            - azurite

    bankclient:
        image: ${ANTITHESIS_REGISTRY}/orleans-bank-test/bankclient:${TAG}
        build:
            dockerfile: Dockerfile.client
        container_name: bankclient
        restart: always
        depends_on:
            - bankserver1
            - bankserver2

    config:
        image: ${ANTITHESIS_REGISTRY}/orleans-bank-test/config:${TAG}
        build:
            dockerfile: Dockerfile.config
        profiles:
            - config